### ISSUE TITLE
add system image fails

### ISSUE THREAD

**Issue by rondie** [stman/OpenWRT-19.07.2-factory-tar-file-for-Ubiquiti-EdgeRouter-x#4]
Following https://openwrt.org/inbox/toh/ubiquiti/ubiquiti_edgerouter_x_er-x_ka#factory_firmware_installation (download link there is broken), I've tried the tarball from all 3 directories, they all failed for me with the same message:
```
ubnt@ubnt:~$ cd /tmp
ubnt@ubnt:/tmp$ add system image openwrt-ramips-mt7621-ubnt_edgerouter-x-initramfs-factory.tar
Version [v1.10.11.5274269.200221.1028] is about to be replaced
Are you sure you want to replace old version? (Yes/No) [Yes]: 
Checking upgrade image...Upgrade image does not support the device. Upgrade failed.
```

I'm somewhat familiar with openwrt, not with edgeos. I can do some tests if requested before I try to go with a TFTP flash, let me know.

**Comment by rondie** [comment]
I've flashed my ER-X with the TFTP and serial method (https://openwrt.org/inbox/toh/ubiquiti/ubiquiti_edgerouter_x_er-x_ka#serial_installation_with_tftp), so my problem is solved.

If the images in this repository work for someone else it could have been just me, but it may be they no longer work.

**Comment by stman** [comment]
Hello.

I am sure the 3 tar images corresponding for the 3 versions work well because I have been using them on several different EdgeRouter X. Please note that before installing these OpenWRT images, I first reflash the original EdgeRouter X software with the TFTP recovery method, then I apply the hotfix software patch from Ubiquity, and only when I have the EdgeRouter X with its latest original software, I install the OpenWRT "short receipt" image corresponding to the desired version of OpenWRT available on this repository, and then, I upgrade with the corresponding "Stock Version" taken from OpenWRT website.

Please note that these images provided here are for EdgeRouter X model, and were not compiled for the other variants of the router. Some users reported that they were also working for the other variants of the EdgeRouter, but I would recommend to indeed recompile the whole thing for the exact variant of the EdgeRouter, to ensure no hidden issue could happen.

Kind regards,

Frederic

**Comment by stman** [comment]
Tell me if you think I answered well your problem, and sorry for the delay for answering. Maybe I should add on this repository all the necessary procedure, instructions and binary files to recover a bricked EdgeRouter X or a EdheRouter X with a broken OpenWRT, with the original EdgeRouter X software from ubiquity with the TFTP method.

This will be done soon.

Kind regards,

Frederic.

**Comment by rondie** [comment]
I just wanted to make sure these images were working, or if it was just me, which you've answered. My steps or edgeOS version may have been the reason it did not work, if I obtain another EdgeRouter X I will try again. Issue closed!
